CMake: install docs into halide subdirectory of doc dir
halide/Halide pull request #6267
Opened 2021-09-25 12:26 UTC by LebedevRI

`DATA` results in those being installed directly into `${CMAKE_INSTALL_PREFIX}/share`,
while they obviously should go into `${CMAKE_INSTALL_PREFIX}/share/doc/Halide`.

Split off of #6266.

2021-09-27 18:03 UTC, alexreinking commented
For style, this PR should use `TYPE DOC` instead of `DESTINATION ${CMAKE_INSTALL_DOCDIR}`

2021-09-27 18:18 UTC, alexreinking requested changes

2021-09-27 18:18 UTC, alexreinking commented on packaging/CMakeLists.txt
> +        DESTINATION ${CMAKE_INSTALL_DOCDIR})
`TYPE DOC`

2021-09-27 19:30 UTC, alexreinking commented
Should this be changed, too?

https://github.com/halide/Halide/blob/17ec57a23ccb468369577441ed910ae1a4d5f956/packaging/CMakeLists.txt#L211-L215

2021-09-27 22:55 UTC, alexreinking commented
Thanks, I just tested this by hand... it is a clear improvement.

2021-09-27 22:56 UTC, alexreinking approved these changes

2021-09-28 08:36 UTC, merged

2021-09-28 08:36 UTC, alexreinking commented
Merged! Thanks for the patch!

2021-09-28 08:38 UTC, LebedevRI commented
@alexreinking thank you for the review!