Restore support for using V8 as the Wasm JIT interpreter
halide/Halide pull request #6478
Opened 2021-12-07 19:04 UTC by steven-johnson

I've taken the liberty to branch https://github.com/halide/Halide/pull/6429 and finish up the work needed to land it.

This passes locally. The V8-specific code won't (yet) get tested on the buildbots (the script and bots need attention to do so) but it can land without that.

2021-12-07 22:26 UTC, steven-johnson commented
OSX-x86 bot is down for repairs, probably OK to ignore for this

2021-12-09 22:02 UTC, alexreinking requested changes

2021-12-09 22:15 UTC, steven-johnson commented on dependencies/wasm/CMakeLists.txt
> +    target_sources(Halide_v8 INTERFACE ${V8_LIB_PATH})
Good question, I just took this from the source PR branch as-is and it worked -- I will make any and all CMake changes as you suggest :-)

2021-12-09 22:16 UTC, steven-johnson commented on README_webassembly.md
> +This is currently only tested on x86-64-Linux and requires v8 version 9.8.147 as a minimum.
Hm, that could be made to work I guess.

2021-12-09 22:17 UTC, steven-johnson commented on README_webassembly.md
> +      -DV8_LIB_PATH=$HOME/v8/v8/out.gn/x64.release.sample/obj/libv8_monolith.a \
I would be quite surprised if such a thing existed.

2021-12-09 22:25 UTC, alexreinking commented on dependencies/wasm/CMakeLists.txt
> +    set_target_properties(Halide_v8 PROPERTIES EXPORT_NAME v8)
Okay, that's an acceptable answer.

2021-12-09 22:25 UTC, alexreinking commented on README_webassembly.md
> +      -DV8_LIB_PATH=$HOME/v8/v8/out.gn/x64.release.sample/obj/libv8_monolith.a \
If we don't care about packaging, then it doesn't matter.

2021-12-09 22:27 UTC, alexreinking commented on README_webassembly.md
> +This is currently only tested on x86-64-Linux and requires v8 version 9.8.147 as a minimum.
It was just a stray thought... maybe worth it if we add a third backend (if one even exists?).

2021-12-09 22:28 UTC, alexreinking commented
Okay, I think I'd like to see the `target_sources` / `target_link_libraries` comments addressed. If we don't care about packaging this, then none of the other stuff matters.

2021-12-09 23:04 UTC, steven-johnson commented on src/CMakeLists.txt
> +    target_link_libraries(Halide PRIVATE ${V8_LIB_PATH})
ok, this is weird: if I *remove* the second line, I get *duplicate symbols* errors when linking. Leaving it like this works. Investigating.

2021-12-09 23:17 UTC, alexreinking commented on dependencies/wasm/CMakeLists.txt
> +    target_sources(Halide_v8 INTERFACE ${V8_LIB_PATH})
Actually, this whole thing should be:

```
add_library(Halide::V8 STATIC IMPORTED)
set_target_properties(Halide::V8 PROPERTIES IMPORTED_LOCATION "${V8_LIB_PATH}")
target_include_directories(Halide::V8 INTERFACE "${V8_INCLUDE_PATH}")
```

and then in `src/CMakeLists.txt` link only to `Halide::V8`.

2021-12-09 23:29 UTC, steven-johnson commented on src/CMakeLists.txt
> +    target_link_libraries(Halide PRIVATE ${V8_LIB_PATH})
It turns out that both LLVM and V8 define a toplevel symbol named `__jit_debug_descriptor`, for GDB integration... which produces link errors, and the previous wonky CMake rules managed to defeat this via, uh, I dunno. V8 needs to be built with `v8_enable_gdbjit = false` to make this work.

2021-12-09 23:36 UTC, alexreinking commented on src/CMakeLists.txt
> +    target_link_libraries(Halide PRIVATE ${V8_LIB_PATH})
Was the library appearing twice on the link line?

2021-12-09 23:37 UTC, steven-johnson commented on README_webassembly.md
> +This is currently only tested on x86-64-Linux and requires v8 version 9.8.147 as a minimum.
I'm inclined to leave this as-is for now. Will revisit later if needed.

2021-12-09 23:38 UTC, alexreinking commented on src/CMakeLists.txt
> +    target_link_libraries(Halide PRIVATE ${V8_LIB_PATH})
This is a biiiig wtf. We should ensure we're building V8 without gdbjit or at _least_ get to the bottom of this and add a comment explaining what is going on here and why it works (for now).

2021-12-09 23:57 UTC, steven-johnson commented on src/CMakeLists.txt
> +    target_link_libraries(Halide PRIVATE ${V8_LIB_PATH})
Yes, rebuilding without gdbjit solves the link issue. Why it works with the current/previous CMake rules is a matter I don't care to spend time investigating.

2021-12-10 00:00 UTC, steven-johnson commented on dependencies/wasm/CMakeLists.txt
> +    target_sources(Halide_v8 INTERFACE ${V8_LIB_PATH})
OK, this is weird; I changed the deps/wasm/CMakeLists.txt like so:

    message(STATUS "Using V8")
    add_library(Halide_V8 STATIC IMPORTED)
    set_target_properties(Halide_V8 PROPERTIES IMPORTED_LOCATION "${V8_LIB_PATH}")
    target_include_directories(Halide_V8 INTERFACE "${V8_INCLUDE_PATH}")

and in src/CMakeLists.txt, like so:

```
if (TARGET Halide_V8)
    target_link_libraries(Halide PRIVATE Halide_V8)
    target_compile_definitions(Halide PRIVATE WITH_V8)
else()
    message(FATAL_ERROR "V8 not found")
endif ()
```

...and it always fails at the fatal error. Is there something about "IF TARGET" that is wonky with imported libs?

2021-12-10 00:09 UTC, alexreinking commented on dependencies/wasm/CMakeLists.txt
> +    target_sources(Halide_v8 INTERFACE ${V8_LIB_PATH})
Ugh, yes... need to make it `STATIC IMPORTED GLOBAL`.

2021-12-10 00:18 UTC, steven-johnson commented on dependencies/wasm/CMakeLists.txt
> +    target_sources(Halide_v8 INTERFACE ${V8_LIB_PATH})
aw yeah

2021-12-10 00:44 UTC, steven-johnson commented
PTAL

2021-12-10 10:46 UTC, alexreinking approved these changes

2021-12-13 22:42 UTC, alexreinking commented
Is this good to merge? Have you looked at the win64 failure?

2021-12-13 23:01 UTC, steven-johnson commented
There's no way thhe windows failure is related, but I will sync to head and retry.

2021-12-14 00:32 UTC, merged