Rename Output to OutputFile and deprecated Output
halide/Halide pull request #6568
Opened 2022-01-19 19:16 UTC by abadams

It would be nice in future if we could promote Generator::Input and
Generator::Output to the Halide namespace. For that to happen, we need
to rename the enum Output first. This PR adds a new name for it, and
deprecates the old name. 

Not married to the name OutputFile. Other suggestions welcome.

2022-01-19 19:28 UTC, steven-johnson requested changes
Should update the Python versions of these enums to use the same nomenclature, see PyEnums.cpp

Re the name, OutputFile is ok with me, but also maybe OutputFileType or OutputType?

2022-01-19 19:28 UTC, steven-johnson commented on src/Module.h
> +class [[deprecated("Use OutputFile instead of Output")]] Output {
IMHO we should still prefer to use `HALIDE_ATTRIBUTE_DEPRECATED()` here, as it allows downstream folks to disable it via `HALIDE_ALLOW_DEPRECATED`

2022-01-19 19:57 UTC, zvookin commented
I hate to ask this, and feel free to ignore if it doesn't make sense... The word "type" is heavily overloaded in a compiler project to begin with and I've come to think being careful around its use is a good idea. Specifically trying to use other words when one is not actually talking about a type in either the source or implementation language. E.g. an "output type" would be the type (buffer of ints or something) of an output.

To that end, maybe "OutputKind" is better. We're already using Kind in some places.

This is not a thing I'd object to the PR over, but figured I'd mention it in case improving our words and consistent use of them seems like a thing to do here.

2022-01-20 18:07 UTC, steven-johnson commented
> To that end, maybe "OutputKind" is better. We're already using Kind in some places.

SGTM, +1

2022-01-21 22:26 UTC, steven-johnson approved these changes

2022-01-25 17:57 UTC, steven-johnson commented
LGTM

2022-01-25 19:43 UTC, steven-johnson commented
Win32 is apparently unrelated (see https://github.com/halide/Halide/pull/6581 for hopeful fix), LGTM to land once green

2022-01-25 20:21 UTC, merged