Inline into extern function args during bounds inference
halide/Halide pull request #7261
Opened 2022-12-29 16:57 UTC by abadams

Fixes #7260

2022-12-30 19:07 UTC, steven-johnson requested changes
Looks good so far, but every bot is failing...

2022-12-30 19:07 UTC, steven-johnson commented on src/BoundsInference.cpp
> +class Inliner : public IRMutator {
nit: worth inserting a comment here about why this is necessary in addition to the previously existing inliner elsewhere

2023-01-01 22:59 UTC, abadams commented
Failing the test python_correctness_realize_warnings because it only prints the warning twice instead of three times. I'm confused about why it would print it more than once. Any ideas?

2023-01-01 23:02 UTC, abadams commented
I just changed the test to assert that the warning is printed at least once, and that nothing else is printed.

2023-01-01 23:16 UTC, steven-johnson commented
I guess the more interesting question here is how/why this PR caused any difference in that at all, whether or not the test made good sense in the first place...

2023-01-05 19:47 UTC, steven-johnson approved these changes
LGTM

2023-01-05 21:12 UTC, merged