Fix Anderson2021 tests to avoid spurious failures on non-Cuda systems
halide/Halide pull request #7518
Opened 2023-04-17 19:41 UTC by steven-johnson

The Anderson2021 autoscheduler is pretty Cuda-specific, so some tests assume it is present; this is pretty much never true on macOS, and annoying spurious failures are annoying. This adds a new flag and capability to RunGenMain to try to sniff out the necessary runtime setup and make it a quiet [SKIP] failure when testing.

2023-04-19 16:55 UTC, steven-johnson commented
The Windows errors make no bloody sense: the errors are reported on lines 557 and 559, but the descriptions don't fit the source at all.

2023-04-21 17:55 UTC, steven-johnson commented
Finally building, PTAL

2023-04-21 20:24 UTC, pranavb-ca requested changes

2023-04-21 20:24 UTC, pranavb-ca commented on tools/RunGenMain.cpp
> +        If the Generator is build for a runtime environment we don't have available
``s/build/built/``

2023-04-21 20:24 UTC, pranavb-ca commented on tools/RunGenMain.cpp
> +            void *cuda_intf = halide_get_symbol("halide_cuda_device_interface");
<nit> consider moving this check to the start of this ``if`` block so we exit early in the instances that we need to.

2023-04-21 21:33 UTC, steven-johnson commented
PTAL

2023-04-21 21:37 UTC, pranavb-ca approved these changes

2023-04-24 01:06 UTC, merged