Add missing deps for some autoscheduler tests
halide/Halide pull request #7605
Opened 2023-06-01 23:21 UTC by steven-johnson

Autoscheduler tests that rely on the relevant shared library being available at runtime need to add a dependency to ensure this is the case.

2023-06-03 17:27 UTC, alexreinking requested changes
Just want to clarify something before approving... the `DEPENDS` test property does not establish dependencies on targets, but on other tests.

2023-06-03 17:27 UTC, alexreinking commented on test/autoschedulers/li2018/CMakeLists.txt
> +                             DEPENDS Li2018
Is there a test named `Li2018`? Should this be the following?
```suggestion
                             DEPENDS li2018_test
```

2023-06-04 22:34 UTC, steven-johnson commented
PTAL

2023-06-05 01:00 UTC, alexreinking approved these changes

2023-06-05 19:16 UTC, merged