Default WITH_TEST_FUZZ to OFF
halide/Halide pull request #7695
Opened 2023-07-20 22:57 UTC by steven-johnson

Just because our compiler supports fuzzing doesn't mean we want to build the fuzz tests, because they won't really build properly without the right preset specified.

(This will be followed up with a change to the buildbot to set WITH_TEST_FUZZ to ON for fuzz tests)

attn: @TH3CHARLie

2023-07-20 23:04 UTC, TH3CHARLie commented
want to add to the reasons for not enabling them, with fuzzer linked, whenever you call `f.realize` you will get something like this:
```
Internal Error at /home/xuanda/dev/Serializer/Halide/src/JITModule.cpp:226 triggered by user code at : Condition failed: addr: Failed to materialize symbols: { (main, { blur_y_metadata, blur_y, $.blur_y.__inits.0, __orc_init_func.blur_y, sancov.module_ctor_8bit_counters, blur_y_argv }) }
```
Not sure about the exact reason, but most likely because libfuzz will insert some kind of `main` into the code already.

2023-07-24 17:23 UTC, steven-johnson commented
Monday morning review ping

2023-07-25 15:38 UTC, alexreinking requested changes

2023-07-25 16:38 UTC, steven-johnson commented
> What doesn't work, exactly? The idea was that HAS_FUZZ_FLAGS was a sufficient condition on the environment for the fuzz tests to be expected to work. What is the true condition?

The fuzzer tests *must* be built using the `linux-x64-fuzzer` preset

2023-07-25 17:57 UTC, alexreinking commented
> The fuzzer tests _must_ be built using the `linux-x64-fuzzer` preset

That's kind of my question... why? What does the preset do that's special? The only non-standard thing I see is that it uses static Halide (so `BUILD_SHARED_LIBS=OFF`),

2023-07-25 18:24 UTC, TH3CHARLie commented
> > The fuzzer tests _must_ be built using the `linux-x64-fuzzer` preset
> 
> That's kind of my question... why? What does the preset do that's special? The only non-standard thing I see is that it uses static Halide (so `BUILD_SHARED_LIBS=OFF`),

I believe it's the new flag making it special:https://github.com/halide/Halide/blob/fd9bfc835f658d8f9d64cff59c64a4503298030d/cmake/toolchain.linux-x64-fuzzer.cmake#L20-L25

2023-07-25 20:17 UTC, abadams commented
e.g. it injects its own int main!

2023-07-26 22:21 UTC, alexreinking approved these changes

2023-07-26 22:25 UTC, merged