[api] Promote Internal::Parameter to Halide::Parameter
halide/Halide pull request #7829
Opened 2023-09-01 18:07 UTC by derek-gerstmann

As per the discussion regarding refactoring the Serialization API: 
https://github.com/halide/Halide/pull/7760

2023-09-01 18:16 UTC, steven-johnson reviewed
From a quick skim, it looks like this change is simpy moving it into the right namespace -- we also need to take a close look at the methods that Parameter exposes (including the ctors); IMHO we want to prune it down to the bare minimum we think are necessary (enforcing via `friend` access if necessary), because otherwise we'll end up with a lot of weird usage we didn't expect (https://www.hyrumslaw.com/).

Once that is done, we will also need to provide a proper Python wrapper for the resulting API; the current Python wrapper (in PyParam.cpp) is deliberately a bare-minimum wrapper that was put in place only for some internal use, but with Parameter become a public Halide object, we need to ensure the Python wrapper provides the same.

2023-09-01 19:27 UTC, derek-gerstmann commented
> From a quick skim, it looks like this change is simpy moving it into the right namespace -- we also need to take a close look at the methods that Parameter exposes (including the ctors); IMHO we want to prune it down to the bare minimum we think are necessary (enforcing via `friend` access if necessary), because otherwise we'll end up with a lot of weird usage we didn't expect (https://www.hyrumslaw.com/).
> 
> Once that is done, we will also need to provide a proper Python wrapper for the resulting API; the current Python wrapper (in PyParam.cpp) is deliberately a bare-minimum wrapper that was put in place only for some internal use, but with Parameter become a public Halide object, we need to ensure the Python wrapper provides the same.

Agreed. I intentionally left obvious internal methods (like `remove_self_references` and `restore_self_references`) hidden, but I didn't got so far as to change the class interface, since I wasn't entirely sure of the impact.

2023-09-08 17:34 UTC, derek-gerstmann commented
I made the raw_buffer(), scalar_address(), and scalar_raw_value() access methods protected, and added Pipeline and Serializer as protected friends.

I believe these are the only potentially controversial class methods which expose addresses and internal values.

2023-09-12 19:19 UTC, steven-johnson requested changes
LGTM but I think we need to also flush out the Python wrapper for `Parameter` -- as mentioned elsewhere, the Python wrapper is currently just a minimal stub for internal use, but with this change, we need to promote it to full public status, and provide all the public methods in Python as well as C++.

2023-09-12 19:19 UTC, steven-johnson commented on src/Generator.cpp
> +    std::map<std::string, Parameter> params;  // FIXME: Remove when API allows this to be optional
Is there an issue tracking this?

2023-09-15 01:12 UTC, derek-gerstmann commented on src/Generator.cpp
> +    std::map<std::string, Parameter> params;  // FIXME: Remove when API allows this to be optional
Just added this as #7849

2023-09-15 01:13 UTC, derek-gerstmann commented
> LGTM but I think we need to also flush out the Python wrapper for `Parameter` -- as mentioned elsewhere, the Python wrapper is currently just a minimal stub for internal use, but with this change, we need to promote it to full public status, and provide all the public methods in Python as well as C++.

Should we update the python bindings in this PR or open a new one?

2023-09-15 01:38 UTC, steven-johnson commented
> > LGTM but I think we need to also flush out the Python wrapper for `Parameter` -- as mentioned elsewhere, the Python wrapper is currently just a minimal stub for internal use, but with this change, we need to promote it to full public status, and provide all the public methods in Python as well as C++.
> 
> Should we update the python bindings in this PR or open a new one?

Unless there is an urgent reason we need to land this quickly, I think it would be better to work out the Python bindings in this PR as well; I've found it a useful exercise in the past to winnow out the calls that are actually necessary for the public API from the ones that aren't.

2023-09-15 19:02 UTC, steven-johnson approved these changes
LGTM pending green

2023-09-15 19:02 UTC, steven-johnson commented on python_bindings/src/halide/halide_/PyParameter.cpp
> +
nit: no blank line at start of func, please

2023-09-18 17:05 UTC, steven-johnson commented
LGTM

2023-09-18 17:09 UTC, merged